name: Deploy Project

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull & Redeploy
        run: |
          cd /root/apps/sechat
          git restore .
          git pull origin main
          docker compose down
          docker compose up -d --build